workflows:
  dev:
    name: Dev
    max_build_duration: 120
    environment:
      flutter: 3.3.0
      xcode: 14.2
      java: 17
      cocoapods: default
    scripts:
      - flutter channel beta
      - flutter upgrade
      - flutter build apk --release --flavor dev -t lib/main_dev.dart
      - flutter build ios --release --flavor dev --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          -  nireekshashetty0402@gmail.com
      firebase:
        firebase_token: 1//0gnq2pcEn2DCFCgYIARAAGBASNwF-L9IrMX40NbJZZB5sK7--Ux-MXMQSYtZjqwNwCDsmKj5gI-epMhd55DxtvVmD5dOi_4GuZzg
        ios:
          app_id: 1:152131913233:ios:aa1c6a73ce32e4863553b0
          groups:
            - member-ios
        android:
          app_id: 1:152131913233:android:b227ea7688f5cc673553b0
          groups:
            - member-android
