workflows:
  dev:
    name: Dev
    max_build_duration: 120
    environment:
      flutter: 3.3.0
      xcode: 14.2
      java: 17
      cocoapods: default
    scripts:
      - flutter channel beta
      - flutter upgrade
      - flutter build apk --release --flavor dev -t lib/main_dev.dart
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          -  nireekshashetty0402@gmail.com