workflows:
  dev:
    name: Dev
    max_build_duration: 120
    environment:
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: Encrypted(KkcqyzHtsuzllJSnUHa16Mohsfee5Yd9jUCW3NB44i5fZuAPVakaapbDz3XZ7m2oIZNs5yrohckFwQ9zzR3TULGl3W1zr2+PgsF7cFq42vSe6Nd6Zs2TS0LXYGq4/yTAo9cIDN9pnqeb5B4Lb94+A9qs839Hhjuv1DzcV4m0Vw8Ktls+HXWc9V3QswnPe4OEDGtSOx6JO3qNrRAVrZH8IrdVRScibjcrWG1DScHZYn+ndoqDopeoxsoezcrQ1bWW0R8hiTwL3eLolNeppl+uokfJ3LuemlX8TJBM4UdUxqO1Yjq5S5P8ftLqLAh936VVV67Oh8/LB2C+JgwRI/iG5BhCo5P83tNlPEFbGna2I43RqIEdedFQJ0+GpBvj0p6D4sNogBIvf4sU56lWnIZMkHv+SUFHoTxayCbMuRAEtWWNWrmgB1LZ2+bNk4JVwZjRI7cFoGnkxKAq9tVmp0jbG9EkxuEzJ/H8wLYO7oLA+ngVxs44zt1El4kRiW/fgGGkxQfqcwwYX9+H4K4g8nwnzeKybec0pKmoMaNbm8rmeZnNwAwUJiN2Zwcps/4aVFC0FCZh4iuUMviAbP/UBKFxplgIszwubWpcTchCbQXgppP1Wh+LAY61OglTaB3NrHcCMXsSNIlPUpz4V9YUiIMI6DybzB4eevbc3RTKIkLkUpTZBTDWkNqVMlB9AkMJjbMttj3bwnjl3gXE+SZwxlkAgzm4VAzcUmRyY8/ekIVrBB/7ig9xjjRuJC8ID2wM6HppIOkzMpZL19vXKocasrkD82rAa+YxOW9Su6fZN2GqswSQq/Gd+LTkIYJ+rm1Te8/WplHqxzyxTLgwiihlqWFrtZgCAWefE8Hn0/56NFBWl/RLMu/PnrnocMORDrDT9jjBYRjg6m+nkbM6x+UF/BGaGOjt0uDWRoCf3eydQb1uyFe/DXqp+lANe7UPA+3jZHtzrn5yb1gXJaG893ND2WQ+KxVmMy8+X9s84RQaEFxzHTB//qkFK2h3GvyUg70FSy/uanp9hR4ui2u1UBu3g1DCzr1lQK6sl/Ftc6+1OsYICq02ZfvtUfpjU9woYWVQbZLia6ZHShUs65vMfbohcxSzSYv1kWEBTiCxWI+betWp7mPGhoLcLpjruVyCoibrhVY1vliTvRgECEqmPZRUqkOxMs3dWDecPQQuhx6OFUPWL5FfBzVNDMkD3EtZJeHtH40NPvw4ZL+izyA1YsnMC9gQR08tMhuAuPQRxZ+7dv2Eitp+YlmmPaq45CSmc7PuBfBImbeZprZ9/zKX7aLO4/dYOc/jZoOwswjxwJtuW4tcTyDO7TWPnHFgHhA0qEXLUnQ03O11DyEWad591hsnYg352OhNdc2NwVEFg4S5x9UOvFllY9mWkv+K9xncMZfkDTUbX5CiHLDUs6l9nmObcg8SlyjfBcwb6RgdQ6vp32uEA8EZukjwEjVLrjNbq66Y7tvKWXx6o46HlILg76uXr+WpaejptZq3f3VQ21kQZoj2cgzLXyGsUdW/E/2XK2uS7gp+62ol7e/OTYAAAAAQAFWC41MDkAAANjMIIDXzCCAkegAwIBAgIETNO8KDANBgkqhkiG9w0BAQsFADBfMQswCQYDVQQGEwI5MTELMAkGA1UECBMCOTExEzARBgNVBAcTCmJhbmFnYWxvcmUxDzANBgNVBAoTBmdhbGF4ZTEPMA0GA1UECxMGZ2FsYXhlMQwwCgYDVQQDEwNtdG0wIBcNMjQwNTA2MDUwNjMyWhgPMjA1MTA5MjIwNTA2MzJaMF8xCzAJBgNVBAYTAjkxMQswCQYDVQQIEwI5MTETMBEGA1UEBxMKYmFuYWdhbG9yZTEPMA0GA1UEChMGZ2FsYXhlMQ8wDQYDVQQLEwZnYWxheGUxDDAKBgNVBAMTA210bTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOluztXe2uR1d3vOaRpDUUzm+Lz9cgfH+rlkhR355cXRz6RNGSu/mBViz+g5/3tTbT7xGHxmFjCVc9dpxo078Dra8HFiZI/MZ4Vh4ox2ujkPYOo+O2/272zGTampiQLT3fIKSkIYUDiIQJNCZpsEAVujeJQB5A59rCt1NiWwEf8nMQFa9aEc1/74Ke9ufWtYudSY4yOKFd4ZwYJBpSYmLTR07nVjfpuPiUyLjMdmiTCAdbNUh6fNjydZI6AQbz8sZv/3RHMAyn9k4WOYUb1SEk9/ijYNfHsO635rygCdOkBbHJ1xBReOGer4wuTRozSMlo40TLf7kUgtTBMqf5UU170CAwEAAaMhMB8wHQYDVR0OBBYEFAfQYEkPaLp4bDUWIRRwCX9IQP97MA0GCSqGSIb3DQEBCwUAA4IBAQCZEBglG8uP09fCUG299AzHvnHsPgklHsIOcTHlWA4EwfhUorimcHQ0Jseci9XO9AmixBN3MckUmhbHUMNPfvYCQkSE9DWWZE03S9I//bGxZJLs2coFiTXvsjTOu9hsScO7eLeSiFkizRGoEULBos+I1zx6bPRiCQ+Zfolzd/x+Wx571P+yPUyVG8RDZSm68O+MEwJpnNJWqVLScYwSxBw7TSkmqcLouNR70MOXJIemXTAqJZlVuQQYG0K6HA63STEYDmX2ig8ETEhkiR+K0h04gGbe9XV5z28nbzP+ryZGV9DxPMp+NpZmBYlhnI89Symai2W6pR9QRjhfY5pyppr+jb4bQAbUQyQN/bakAR0feIPmj/k=)
        FCI_KEYSTORE_PASSWORD: Encrypted(UGdseEAyMDIz)
        FCI_KEY_PASSWORD: Encrypted(UGdseEAyMDIz)
        FCI_KEY_ALIAS: Encrypted(dHJhbnNpdA==)
      flutter: 3.3.0
      xcode: 14.2
      java: 17
      cocoapods: default
    scripts:
    # set up key.properties
      -
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - flutter channel beta
      - flutter upgrade
      - flutter build apk --release --flavor dev -t lib/main_dev.dart
      # - flutter build ios --release --flavor dev --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          -  nireekshashetty0402@gmail.com
      firebase:
        firebase_token: 1//0gnq2pcEn2DCFCgYIARAAGBASNwF-L9IrMX40NbJZZB5sK7--Ux-MXMQSYtZjqwNwCDsmKj5gI-epMhd55DxtvVmD5dOi_4GuZzg
        ios:
          app_id: 1:152131913233:ios:aa1c6a73ce32e4863553b0
          groups:
            - member-ios
        android:
          app_id: 1:152131913233:android:b227ea7688f5cc673553b0
          groups:
            - member-android
